export enum ETopType {
  TRENDING = 'trending',
  TRUSTLINES = 'trustlines',
  TRUSTLINES_DELTA_24H = 'trustlines-delta-24h',
  TRUSTLINES_DELTA_7D = 'trustlines-delta-7d',
  HOLDERS = 'holders',
  HOLDERS_DELTA_24H = 'holders-delta-24h',
  HOLDERS_DELTA_7D = 'holders-delta-7d',
  MARKETCAP = 'marketcap',
  MARKETCAP_DELTA_24H = 'marketcap-delta-24h',
  MARKETCAP_DELTA_7D = 'marketcap-delta-7d',
  PRICE_CHANGE_24H = 'price-change-24h',
  PRICE_CHANGE_7D = 'price-change-7d',
  VOLUME_24H = 'volume-24h',
  VOLUME_7D = 'volume-7d',
  TRADERS_24H = 'traders-24h',
  TRADERS_7D = 'traders-7d',
}
